name: Railway Operation Simulator
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: Build Libraries (${{ matrix.os }})
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Update Clang (macOS)
        run: |
          brew update
          brew upgrade llvm
        if: ${{ matrix.os  == 'macos-latest' }}
      - name: Set environment (macOS)
        run: |
          export CXX="/usr/local/opt/llvm/bin/clang++"
          export CC="/usr/local/opt/llvm/bin/clang"
        if: ${{ matrix.os == 'macos-latest' }}
      - name: Setup CMake
        uses: lukka/get-cmake@latest
      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@v1.1
      - name: Configure CMake
        run: |
          cmake -Bbuild -G Ninja -DCMAKE_EXPORT_COMPILE_COMMANDS=1
          mv build/compile_commands.json .
      - name: Run Build
        run: cmake --build build -j8
  linting:
    runs-on: ubuntu-latest
    name: C++ Linting
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run Linter
        uses: ArtificialAmateur/cpp-linter-action@master
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}